# Configuration parameters for data recording node.

output_directory: '/home/example/rosbags'

topics:
  - '/example/(.*)'
  - '/camera/depth/image_raw'
  - '/camera/depth/camera_info'
  - '/camera/rgb/image_raw'
  - '/camera/rgb/camera_info'
